### ISSUE TITLE
fork下来试一试，Android5.0.2闪退

### ISSUE THREAD

**Issue by winlandiano** [MaybeMercy/zhihutoday#1]
呃……您为什么要把资源图片好多都ignore了，只是单纯不理解。

RT, Android5.0.2闪退。logcat：
04-23 02:10:52.869: E/AndroidRuntime(31597): FATAL EXCEPTION: main
04-23 02:10:52.869: E/AndroidRuntime(31597): Process: com.example.zhihupocket, PID: 31597
04-23 02:10:52.869: E/AndroidRuntime(31597): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.zhihupocket/com.example.zhihupocket.StoryContent}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
04-23 02:10:52.869: E/AndroidRuntime(31597): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2301)
04-23 02:10:52.869: E/AndroidRuntime(31597): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2361)
04-23 02:10:52.869: E/AndroidRuntime(31597): 	at android.app.ActivityThread.access$800(ActivityThread.java:147)
04-23 02:10:52.869: E/AndroidRuntime(31597): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)
04-23 02:10:52.869: E/AndroidRuntime(31597): 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-23 02:10:52.869: E/AndroidRuntime(31597): 	at android.os.Looper.loop(Looper.java:135)
04-23 02:10:52.869: E/AndroidRuntime(31597): 	at android.app.ActivityThread.main(ActivityThread.java:5233)
04-23 02:10:52.869: E/AndroidRuntime(31597): 	at java.lang.reflect.Method.invoke(Native Method)
04-23 02:10:52.869: E/AndroidRuntime(31597): 	at java.lang.reflect.Method.invoke(Method.java:372)
04-23 02:10:52.869: E/AndroidRuntime(31597): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
04-23 02:10:52.869: E/AndroidRuntime(31597): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
04-23 02:10:52.869: E/AndroidRuntime(31597): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
04-23 02:10:52.869: E/AndroidRuntime(31597): 	at com.example.zhihupocket.StoryContent.onCreate(StoryContent.java:37)
04-23 02:10:52.869: E/AndroidRuntime(31597): 	at android.app.Activity.performCreate(Activity.java:5941)
04-23 02:10:52.869: E/AndroidRuntime(31597): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
04-23 02:10:52.869: E/AndroidRuntime(31597): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2254)

不知道是不是我的项目结构有问题

**Comment by MaybeMercy** [comment]
我把res/和libs/都上传上去了，自己没有fork过……sorry

**Comment by jasonlvhit** [comment]
。。。神对话。。。。

**Comment by winlandiano** [comment]
我去…乌龙了……
